<?php

return array(
    'PhpBoletoZf2\Controller\BBController' => __DIR__ . '/Controller/BBController.php',
    'PhpBoletoZf2\Controller\BradescoController' => __DIR__ . '/Controller/BradescoController.php',
    'PhpBoletoZf2\Controller\CaixaSigcbController' => __DIR__ . '/Controller/CaixaSigcbController.php',
    'PhpBoletoZf2\Controller\ItauController' => __DIR__ . '/Controller/ItauController.php',
    'PhpBoletoZf2\Factory\AbstractBoletoFactory' => __DIR__ . '/Factory/AbstractBoletoFactory.php',
    'PhpBoletoZf2\Factory\BB' => __DIR__ . '/Factory/BB.php',
    'PhpBoletoZf2\Factory\Bradesco' => __DIR__ . '/Factory/Bradesco.php',
    'PhpBoletoZf2\Factory\CaixaSigcb' => __DIR__ . '/Factory/CaixaSigcb.php',
    'PhpBoletoZf2\Factory\Itau' => __DIR__ . '/Factory/Itau.php',
    'PhpBoletoZf2\Form\Boleto' => __DIR__ . '/Form/Boleto.php',
    'PhpBoletoZf2\Form\BoletoFilter' => __DIR__ . '/Form/BoletoFilter.php',
    'PhpBoletoZf2\Lib\Barcode\Renderer\Base64' => __DIR__ . '/Lib/Barcode/Renderer/Base64.php',
    'PhpBoletoZf2\Lib\Util' => __DIR__ . '/Lib/Util.php',
    'PhpBoletoZf2\Model\AbstractBoleto' => __DIR__ . '/Model/AbstractBoleto.php',
    'PhpBoletoZf2\Model\Banco' => __DIR__ . '/Model/Banco.php',
    'PhpBoletoZf2\Model\BancoInterface' => __DIR__ . '/Model/BancoInterface.php',
    'PhpBoletoZf2\Model\BoletoBB' => __DIR__ . '/Model/BoletoBB.php',
    'PhpBoletoZf2\Model\BoletoBradesco' => __DIR__ . '/Model/BoletoBradesco.php',
    'PhpBoletoZf2\Model\BoletoCaixa' => __DIR__ . '/Model/BoletoCaixa.php',
    'PhpBoletoZf2\Model\BoletoInterface' => __DIR__ . '/Model/BoletoInterface.php',
    'PhpBoletoZf2\Model\Cedente' => __DIR__ . '/Model/Cedente.php',
    'PhpBoletoZf2\Model\CedenteInterface' => __DIR__ . '/Model/CedenteInterface.php',
    'PhpBoletoZf2\Model\Sacado' => __DIR__ . '/Model/Sacado.php',
    'PhpBoletoZf2\Model\SacadoInterface' => __DIR__ . '/Model/SacadoInterface.php',
    'PhpBoletoZf2\Module' => __DIR__ . '/Module.php',
);
