<html>
    <head>
        <title>
            <?php echo $this->dados->getCedente()->getIdentificacao(); ?>
        </title>
        <meta http-equiv=Content-Type content=text/html charset=UTF-8 />
        <meta name="Generator" content="Projeto BoletoPHP para Zend Framework 2 - www.boletophp.com.br - Licença GPL" />
        <style type=text/css>@page {margin-top: 0.6em;margin-left: 0.6em;}body {padding: 5px;margin: 0;}table { margin: 0; padding: 0; border-spacing: 0; border-collapse: collapse; }td {margin: 0; padding: 0;}.cp { font: bold 10px Arial; color: #000000}.ti { font: 9px Arial, Helvetica, sans-serif}.ld { font: bold 15px Arial; color: #000000}.ct { FONT: 9px "Arial Narrow"; COLOR: #000033}.cn { FONT: 9px Arial; COLOR: black }.bc { font: bold 20px Arial; color: #000000 }.ld2 { font: bold 12px Arial; color: #000000 }</style> </head>
    <body text=#000000 bgColor=#ffffff topMargin=0 rightMargin=0>
        <table width="666" border="0">
            <tr>
                <td valign=top class=cp>
                    <div style="text-align: center">Instruções de Impressão</div>
                </td>
            </tr>
            <tr>
                <td valign=top class=cp>
                    <ul>
                        <li>Imprima em impressora jato de tinta (ink jet) ou laser em qualidade normal ou alta (Não use modo econômico).<br />
                        <li>Utilize folha A4 (210 x 297 mm) ou Carta (216 x 279 mm) e margens mínimas à esquerda e à direita do formulário.<br />
                        <li>Corte na linha indicada. Não rasure, risque, fure ou dobre a região onde se encontra o código de barras.<br />
                        <li>Caso não apareça o código de barras no final, pressione a tecla F5 para atualizar esta tela.<li>Caso tenha problemas ao imprimir, copie a sequência numérica abaixo e pague no caixa eletrônico ou no internet banking:<br />
                            <br />
                            <span class="ld2">&nbsp;&nbsp;&nbsp;&nbsp;Linha Digitável: &nbsp;<img src="<?php echo $this->dados->getBoleto()->getLinhaDigitavel('base64')->render() ?>" />
                                <br />&nbsp;&nbsp;&nbsp;&nbsp;Valor: &nbsp;&nbsp;R$ <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ",", "") ?>
                                <br />
                            </span>
                        </li>
                    </ul>
                </td>
            </tr>
        </table>
        <br />
        <table width="666" border="0">
            <tbody>
                <tr>
                    <td class=ct width="666">
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAApkAAAACAQAAAAA76vpWAAAAGUlEQVR42mNgbDiQYCDBw8ZMPUYDAy0MBQCvGyXfT4/GUQAAAABJRU5ErkJggg==" width=665 border="0">
                    </td>
                </tr>
                <tr>
                    <td class=ct width="666">
                        <div style="text-align: right">
                            <b class=cp>Recibo do Sacado</b>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
        <table width="666" cellspacing=5 cellpadding="0" border="0">
            <tr>
                <td width=41>
                </td>
            </tr>
        </table>
        <table width="666" cellspacing=5 cellpadding="0" border="0" align=Default>
            <tr>
                <td width=41>
                    <IMG SRC="<?php echo $this->dados->getCedente()->getLogoCedente() ?>">
                </td>
                <td class=ti width=455>
                    <?php echo $this->dados->getCedente()->getIdentificacao(); ?> <?php echo $this->dados->getCedente()->getDocumento() ?>
                    <br>
                    <?php echo $this->dados->getCedente()->getEndereco() ?>
                    <br>
                    <?php echo $this->dados->getCedente()->getCidade() . '/' . $this->dados->getCedente()->getUf() ?>
                    <br>
                </td>
                <td align=RIGHT width=150 class=ti>&nbsp;</td>
            </tr>
        </table>
        <br />
        <table width="666" border="0">
            <tr>
                <td class=cp width=150> <span class="campo">
                        <IMG src="<?php echo $this->dados->getBanco()->getLogoBanco() ?>" width="150" height="40" border="0">
                    </span>
                </td>
                <td width=3 valign=bottom>
                    <img height=22 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=2 border="0">
                </td>
                <td class=cpt width=58 valign=bottom>
                    <div align=center>
                        <font class=bc>
                        <?php echo $this->dados->getBanco()->getCodigoBanco() . '-' . $this->dados->getBanco()->getCodigoBancoDv() ?>
                        </font>
                    </div>
                </td>
                <td width=3 valign=bottom>
                    <img height=22 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=2 border="0">
                </td>
                <td class=ld align=right width=453 valign=bottom>
                    <span class=ld> <span class="campotitulo">
                            <img src="<?php echo $this->dados->getBoleto()->getLinhaDigitavel('base64')->render() ?>" />
                        </span>
                    </span>
                </td>
            </tr>
            <tbody>
                <tr>
                    <td colspan=5>
                        <img height=2 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width="666" border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=298 height=13>Cedente</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=126 height=13>Agência/Código do Cedente</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=34 height=13>Espécie</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=53 height=13>Quantidade</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=120 height=13>Nosso número</td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=298 height=12> <span class="campo">
                            <?php echo $this->dados->getCedente()->getNomeCedente(); ?>
                        </span>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=126 height=12> <span class="campo">
                            <?php echo $this->dados->getCedente()->getAgenciaCodigo() ?>
                        </span>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=34 height=12>
                        <span class="campo">
                            <?php echo $this->dados->getBanco()->getEspecie() ?>
                        </span> </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=53 height=12>
                        <span class="campo">
                            <?php echo $this->dados->getBoleto()->getQuantidade() ?>
                        </span> </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=120 height=12> <span class="campo">
                            <?php echo $this->dados->getBoleto()->getNossoNumeroFormatado() ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=298 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=298 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=126 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=126 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=34 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=34 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=53 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=53 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=120 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=120 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top colspan=3 height=13>Número do documento</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=132 height=13>CPF/CNPJ</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=134 height=13>Vencimento</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=180 height=13>Valor documento</td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top colspan=3 height=12> <span class="campo">
                            <?php echo $this->dados->getBoleto()->getNumeroDocumento() ?>
                        </span>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=132 height=12> <span class="campo">
                            <?php echo $this->dados->getCedente()->getDocumento() ?>
                        </span>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=134 height=12> <span class="campo">
                            <?php echo $this->dados->getBoleto()->getDataVencimento()->format("d/m/Y") ?>
                        </span>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=180 height=12> <span class="campo">
                            <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ",", "") ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=113 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=113 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=72 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=72 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=132 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=132 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=134 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=134 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=180 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=113 height=13>(-) Desconto / Abatimentos</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=112 height=13>(-) Outras deduções</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=113 height=13>(+) Mora / Multa</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=113 height=13>(+) Outros acréscimos</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=180 height=13>(=) Valor cobrado</td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=113 height=12>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=112 height=12>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=113 height=12>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=113 height=12>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=180 height=12>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=113 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=113 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=112 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=112 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=113 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=113 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=113 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=113 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=180 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=659 height=13>Sacado</td>
                </tr> 
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=659 height=12> <span class="campo">
                            <?php echo $this->dados->getSacado()->getNome() ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=659 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=659 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct width=7 height=12>
                    </td>
                    <td class=ct width=564 >Demonstrativo</td>
                    <td class=ct width=7 height=12>
                    </td>
                    <td class=ct width=88 >Autenticação mecânica</td>
                </tr>
                <tr>
                    <td width=7 >
                    </td>
                    <td class=cp width=564 >
                        <span class="campo">
                            <?php echo $this->dados->getBoleto()->getDemonstrativo1() ?>
                            <br />
                            <?php echo $this->dados->getBoleto()->getDemonstrativo2() ?>
                            <br />
                            <?php echo $this->dados->getBoleto()->getDemonstrativo3() ?>
                            <br />
                        </span>
                    </td>
                    <td width=7 >
                    </td>
                    <td width=88 >
                    </td>
                </tr>
            </tbody>
        </table>
        <table width="666" border="0">
            <tbody>
                <tr>
                    <td width=7>
                    </td>
                    <td width=500 class=cp> <br />
                        <br />
                        <br /> </td>
                    <td width=159>
                    </td>
                </tr>
            </tbody>
        </table>
        <table width="666" border="0">
            <tr>
                <td class=ct width="666">
                </td>
            </tr>
            <tbody>
                <tr>
                    <td class=ct width="666"> <div align=right>Corte na linha pontilhada</div>
                    </td>
                </tr>
                <tr>
                    <td class=ct width="666">
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAApkAAAACAQAAAAA76vpWAAAAGUlEQVR42mNgbDiQYCDBw8ZMPUYDAy0MBQCvGyXfT4/GUQAAAABJRU5ErkJggg==" width=665 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <br />
        <table width="666" border="0">
            <tr>
                <td class=cp width=150> <span class="campo">
                        <IMG src="<?php echo $this->dados->getBanco()->getLogoBanco() ?>" width="150" height="40" border="0">
                    </span>
                </td>
                <td width=3 valign=bottom>
                    <img height=22 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=2 border="0">
                </td>
                <td class=cpt width=58 valign=bottom>
                    <div align=center>
                        <font class=bc>
                        <?php echo $this->dados->getBanco()->getCodigoBanco() . '-' . $this->dados->getBanco()->getCodigoBancoDv() ?>
                        </font>
                    </div>
                </td>
                <td width=3 valign=bottom>
                    <img height=22 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAIAAAATAQMAAACA8k5ZAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=2 border="0">
                </td>
                <td class=ld align=right width=453 valign=bottom>
                    <span class=ld> <span class="campotitulo">
                            <img src="<?php echo $this->dados->getBoleto()->getLinhaDigitavel('base64')->render() ?>" />
                        </span>
                    </span>
                </td>
            </tr>
            <tbody>
                <tr>
                    <td colspan=5>
                        <img height=2 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width="666" border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=472 height=13>Local de pagamento</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=180 height=13>Vencimento</td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=472 height=12>Pagável em qualquer Banco até o vencimento</td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=180 height=12> <span class="campo">
                            <?php echo $this->dados->getBoleto()->getDataVencimento()->format('d/m/Y') ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=472 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=472 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=180 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=472 height=13>Cedente</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=180 height=13>Agência/Código cedente</td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=472 height=12> <span class="campo">
                            <?php echo $this->dados->getCedente()->getNomeCedente() ?>
                        </span>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=180 height=12> <span class="campo">
                            <?php echo $this->dados->getCedente()->getAgenciaCodigo() ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=472 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=472 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=180 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=113 height=13>Data do documento</td>
                    <td class=ct valign=top width=7 height=13> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=153 height=13>N&ordm; documento</td>
                    <td class=ct valign=top width=7 height=13> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=62 height=13>Espécie doc.</td>
                    <td class=ct valign=top width=7 height=13> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=34 height=13>Aceite</td>
                    <td class=ct valign=top width=7 height=13> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=82 height=13>Data processamento</td>
                    <td class=ct valign=top width=7 height=13> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=180 height=13>Nosso número</td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=113 height=12>
                        <div align=left> <span class="campo">
                                <?php echo $this->dados->getBoleto()->getDataDocumento()->format('d/m/Y') ?>
                            </span>
                        </div>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=153 height=12> <span class="campo">
                            <?php echo $this->dados->getBoleto()->getNumeroDocumento() ?>
                        </span>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=62 height=12>
                        <div align=left>
                            <span class="campo">
                                <?php echo $this->dados->getBanco()->getEspecieDoc() ?>
                            </span> </div>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=34 height=12>
                        <div align=left>
                            <span class="campo">
                                <?php echo $this->dados->getBanco()->getAceite() ?>
                            </span> </div>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=82 height=12>
                        <div align=left> <span class="campo">
                                <?php echo $this->dados->getBoleto()->getDataProcessamento()->format('d/m/Y') ?>
                            </span>
                        </div>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=180 height=12> <span class="campo">
                            <?php echo $this->dados->getBoleto()->getNossoNumeroFormatado() ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=113 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=113 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=153 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=153 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=62 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=62 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=34 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=34 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=82 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=82 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=180 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr> <td class=ct valign=top width=7 height=13> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top COLSPAN="3" height=13>Uso do banco</td>
                    <td class=ct valign=top height=13 width=7> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=83 height=13>Carteira</td>
                    <td class=ct valign=top height=13 width=7> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=53 height=13>Espécie</td>
                    <td class=ct valign=top height=13 width=7> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=123 height=13>Quantidade</td>
                    <td class=ct valign=top height=13 width=7> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=72 height=13> Valor Documento</td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=180 height=13>(=) Valor documento</td>
                </tr>
                <tr> <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td valign=top class=cp height=12 COLSPAN="3">
                        <div align=left> </div>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=83> <div align=left> <span class="campo">
                                <?php echo $this->dados->getBanco()->getCarteira() ?>
                            </span>
                        </div>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=53>
                        <div align=left>
                            <span class="campo">
                                <?php echo $this->dados->getBanco()->getEspecie() ?>
                            </span> </div>
                    </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=123>
                        <span class="campo">
                            <?php echo $this->dados->getBoleto()->getQuantidade() ?>
                        </span> </td>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=72> <span class="campo">
                            <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ",", "") ?>
                        </span>
                    </td>
                    <td class=cp valign=top width=7 height=12> <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top align=right width=180 height=12> <span class="campo">
                            <?php echo number_format($this->dados->getBoleto()->getValor() / 100, 2, ",", "") ?>
                        </span>
                    </td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=75 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=31 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=31 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=83 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=83 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=53 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=53 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=123 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=123 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=72 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=72 border="0">
                    </td>
                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=180 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                    </td>
                </tr>
            </tbody> </table>
        <table width="666" border="0">
            <tbody>
                <tr>
                    <td align=right width=10>
                        <table border="0" align=left>
                            <tbody> <tr> <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr> <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr> <td valign=top width=7 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=1 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td valign=top width=468 rowspan=5>
                        <font class=ct>Instruções (Texto de responsabilidade do cedente)</font>
                        <br />
                        <br />
                        <span class=cp> <FONT class=campo>
                            <?php echo $this->dados->getBoleto()->getInstrucoes1() ?>
                            <br />
                            <?php echo $this->dados->getBoleto()->getInstrucoes2() ?>
                            <br />
                            <?php echo $this->dados->getBoleto()->getInstrucoes3() ?>
                            <br />
                            <?php echo $this->dados->getBoleto()->getInstrucoes4() ?>
                            </FONT>
                            <br />
                            <br /> </span>
                    </td>
                    <td align=right width=188>
                        <table border="0">
                            <tbody>
                                <tr>
                                    <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=ct valign=top width=180 height=13>(-) Desconto / Abatimentos</td>
                                </tr>
                                <tr> <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=cp valign=top align=right width=180 height=12>
                                    </td>
                                </tr>
                                <tr> <td valign=top width=7 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                                    </td>
                                    <td valign=top width=180 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td align=right width=10> <table border="0" align=left>
                            <tbody>
                                <tr>
                                    <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr>
                                    <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr>
                                    <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=1 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td align=right width=188>
                        <table border="0">
                            <tbody>
                                <tr>
                                    <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=ct valign=top width=180 height=13>(-) Outras deduções</td>
                                </tr>
                                <tr>
                                    <td class=cp valign=top width=7 height=12> <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=cp valign=top align=right width=180 height=12>
                                    </td>
                                </tr>
                                <tr>
                                    <td valign=top width=7 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                                    </td>
                                    <td valign=top width=180 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td align=right width=10> <table border="0" align=left>
                            <tbody>
                                <tr>
                                    <td class=ct valign=top width=7 height=13> <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr>
                                    <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr>
                                    <td valign=top width=7 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=1 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td align=right width=188> <table border="0">
                            <tbody>
                                <tr>
                                    <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=ct valign=top width=180 height=13>(+) Mora / Multa</td>
                                </tr>
                                <tr>
                                    <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=cp valign=top align=right width=180 height=12>
                                    </td>
                                </tr>
                                <tr> <td valign=top width=7 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                                    </td>
                                    <td valign=top width=180 height=1> <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td align=right width=10>
                        <table border="0" align=left>
                            <tbody>
                                <tr> <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr>
                                    <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr>
                                    <td valign=top width=7 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=1 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td align=right width=188> <table border="0">
                            <tbody>
                                <tr> <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=ct valign=top width=180 height=13>(+) Outros acréscimos</td>
                                </tr>
                                <tr> <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=cp valign=top align=right width=180 height=12>
                                    </td>
                                </tr>
                                <tr>
                                    <td valign=top width=7 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                                    </td>
                                    <td valign=top width=180 height=1>
                                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
                <tr>
                    <td align=right width=10>
                        <table border="0" align=left>
                            <tbody>
                                <tr>
                                    <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                                <tr>
                                    <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                    <td align=right width=188>
                        <table border="0">
                            <tbody>
                                <tr>
                                    <td class=ct valign=top width=7 height=13>
                                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=ct valign=top width=180 height=13>(=) Valor cobrado</td>
                                </tr>
                                <tr>
                                    <td class=cp valign=top width=7 height=12>
                                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                                    </td>
                                    <td class=cp valign=top align=right width=180 height=12>
                                    </td>
                                </tr>
                            </tbody> </table>
                    </td>
                </tr>
            </tbody>
        </table>
        <table width="666" border="0">
            <tbody>
                <tr>
                    <td valign=top width="666" height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width="666" border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=659 height=13>Sacado</td>
                </tr>
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=659 height=12>
                        <span class="campo">

                            <?php
                            if ($this->dados->getSacado()->getDocumento()) {
                                $l = preg_replace("/[^\d]/", "", $this->dados->getSacado()->getDocumento());
                                if (strlen($l) == 11) {
                                    $documento = 'CPF: ';
                                } else {
                                    $documento = 'CNPJ: ';
                                }
                            } else {
                                $documento = '';
                            }
                            ?>
                            <?php echo $this->dados->getSacado()->getNome() . ' - ' . $documento . $this->dados->getSacado()->getDocumento() ?>


                        </span> </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=cp valign=top width=7 height=12>
                        <img height=12 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=659 height=12>
                        <span class="campo">
                            <?php echo $this->dados->getSacado()->getEndereco1() ?>
                        </span> </td>
                </tr>
            </tbody>
        </table>
        <table border="0">
            <tbody>
                <tr>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=cp valign=top width=472 height=13> <span class="campo">
                            <?php echo $this->dados->getSacado()->getEndereco2() ?>
                        </span>
                    </td>
                    <td class=ct valign=top width=7 height=13>
                        <img height=13 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAATAQMAAABrxfVaAAAAA1BMVEUAAACnej3aAAAADElEQVR42mNgIAYAAAAmAAEy2MJFAAAAAElFTkSuQmCC" width=1 border="0">
                    </td>
                    <td class=ct valign=top width=180 height=13>Cód. baixa</td>
                </tr>
                <tr>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=472 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=472 border="0">
                    </td>
                    <td valign=top width=7 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=7 border="0">
                    </td>
                    <td valign=top width=180 height=1>
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAAA1BMVEUAAACnej3aAAAACklEQVR42mNgAAAAAgAB5Sfe/AAAAABJRU5ErkJggg==" width=180 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
        <table border="0" width="666">
            <TBODY>
                <tr>
                    <TD class=ct width=7 height=12>
                    </td>
                    <TD class=ct width=409 >Sacador/Avalista</td>
                    <TD class=ct width=250 >
                        <div align=right>Autenticação mecânica - <b class=cp>Ficha de Compensação</b>
                        </div>
                    </td>
                </tr>
                <tr>
                    <TD class=ct colspan=3 >
                    </td>
                </tr>
            </tbody>
        </table>
        <table width="666" border="0">
            <TBODY>
                <tr>
                    <TD vAlign=bottom align=left height=50>
                        <img src="<?php echo $this->dados->getBoleto()->getCodigoDeBarras()->render() ?>" /> </td>
                </tr>
            </tbody>
        </table>
        <table width="666" border="0">
            <tr>
                <TD class=ct width="666">
                </td>
            </tr>
            <TBODY>
                <tr>
                    <TD class=ct width="666">
                        <div align=right>Corte na linha pontilhada</div>
                    </td>
                </tr>
                <tr>
                    <TD class=ct width="666">
                        <img height=1 src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAApkAAAACAQAAAAA76vpWAAAAGUlEQVR42mNgbDiQYCDBw8ZMPUYDAy0MBQCvGyXfT4/GUQAAAABJRU5ErkJggg==" width=665 border="0">
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
